# -*- coding: utf-8 -*-
"""Untitled13.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CRxldoTTaoFAWWnwRE_yyg7EvVHvd_zz
"""

# STEP 1: Mount Google Drive and install required packages
from google.colab import drive
drive.mount('/content/drive')

!pip install transformers scikit-learn pandas tqdm

# STEP 2: Import libraries
import os
import json
import pandas as pd
from transformers import pipeline
from tqdm import tqdm
from sklearn.metrics import classification_report

# STEP 3: Configuration
BASE_DIR = "/content/drive/MyDrive/allr"  # Dataset path in Google Drive
EVENT = "charliehebdo"                      # One of the PHEME event folders
NUM_RUMOURS = 100
NUM_NON_RUMOURS = 10
MODEL_NAMES = [
    "distilbert-base-uncased-finetuned-sst-2-english",
    "google/electra-small-discriminator",
    "albert-base-v2"
]

# STEP 4: Function to load threads from dataset
def load_annotated_threads(event_dir, category, limit):
    data = []
    path = os.path.join(event_dir, category)
    threads = [d for d in os.listdir(path) if os.path.isdir(os.path.join(path, d))][:limit]
    for thread_id in tqdm(threads, desc=f"Processing {category}"):
        thread_path = os.path.join(path, thread_id)
        source_path = os.path.join(thread_path, "source-tweet", "source-tweet.json")
        reaction_path = os.path.join(thread_path, "reactions")
        annotation_path = os.path.join(thread_path, "annotation.json")

        if not os.path.exists(annotation_path):
            continue

        try:
            with open(source_path, "r", encoding="utf-8") as f:
                context = json.load(f)["text"]
            with open(annotation_path, "r", encoding="utf-8") as f:
                annotations = json.load(f)
        except Exception:
            continue

        for tweet_id, stance in annotations.items():
            reply_file = os.path.join(reaction_path, f"{tweet_id}.json")
            if not os.path.exists(reply_file):
                continue
            try:
                with open(reply_file, "r", encoding="utf-8") as f:
                    reply_text = json.load(f)["text"]
                data.append({
                    "tweet_id": tweet_id,
                    "context": context,
                    "reply": reply_text,
                    "label": stance
                })
            except Exception:
                continue
    return pd.DataFrame(data)

# STEP 5: Load data
event_path = os.path.join(BASE_DIR, EVENT)
df_rumours = load_annotated_threads(event_path, "rumours", NUM_RUMOURS)
df_non_rumours = load_annotated_threads(event_path, "non-rumours", NUM_NON_RUMOURS)
df_all = pd.concat([df_rumours, df_non_rumours]).reset_index(drop=True)

# STEP 6: Prediction label mapping
def map_prediction(label):
    if "NEGATIVE" in label.upper():
        return "deny"
    elif "POSITIVE" in label.upper():
        return "support"
    else:
        return "comment"

# STEP 7: Inference and report generation
for model_name in MODEL_NAMES:
    clf = pipeline("text-classification", model=model_name)
    tqdm.pandas(desc=f"Inference with {model_name}")
    df_all[f"pred_{model_name}"] = df_all["reply"].progress_apply(lambda x: map_prediction(clf(x)[0]["label"]))

    y_true = df_all["label"]
    y_pred = df_all[f"pred_{model_name}"]
    report = classification_report(y_true, y_pred, output_dict=True)
    report_df = pd.DataFrame(report).transpose()
    report_path = f"/content/drive/MyDrive/report_{model_name.replace('/', '_')}.csv"
    report_df.to_csv(report_path)
    print(f"Saved: {report_path}")

import json
from bson import encode  # funzione di livello modulo per serializzare in BSON

# 1. Definisci qui la tua stringa JSON
json_string = '{"nome": "Alice", "età": 30, "attivo": true}'

# 2. Carica il JSON in un oggetto Python (dizionario)
document = json.loads(json_string)

# 3. Serializza il documento in BSON
bson_bytes = encode(document)

# 4. Ottieni i byte della stringa JSON originale in UTF-8
json_bytes = json_string.encode('utf-8')

# 5. Calcola le rappresentazioni esadecimali
json_hex = json_bytes.hex()
bson_hex = bson_bytes.hex()

# 6. Stampa i risultati
print("JSON (hex):", json_hex)
print("BSON (hex):", bson_hex)

import json
from bson import BSON       # classe ufficiale in pymongo
from bson.json_util import loads  # per Extended JSON, opzionale

def json_to_bson(input_json_path: str, output_bson_path: str) -> None:
    # Carica JSON (Extended JSON se serve)
    with open(input_json_path, 'r', encoding='utf-8') as f:
        raw = f.read()
    try:
        doc = loads(raw)  # supporta Extended JSON
    except Exception:
        doc = json.loads(raw)  # JSON puro

    # Serializza in BSON
    bson_data: bytes = BSON.encode(doc)

    # Salva su file binario
    with open(output_bson_path, 'wb') as f:
        f.write(bson_data)

if __name__ == "__main__":
    json_to_bson("input.json", "output.bson")
    print("Conversione completata: 'output.bson' creato.")

!pip install -U datasets
!pip install fsspec==2023.9.2
from datasets import load_dataset

dataset = load_dataset("ucsbnlp/liar")

dataset["train"].column_names

from datasets import load_dataset
from transformers import pipeline
from sklearn.metrics import accuracy_score
from tqdm import tqdm

# STEP 4: Preleva un sottoinsieme (es. primi 500 per test rapido)
subset = dataset["test"].select(range(500))  # o "train", o più esempi

# STEP 5: Mappa numerica -> testo
label_map = {
    0: "pants-fire",
    1: "false",
    2: "barely-true",
    3: "half-true",
    4: "mostly-true",
    5: "true"
}

# STEP 6: Crea un classificatore LLM (sentiment per proxy)
clf = pipeline("text-classification", model="distilbert-base-uncased-finetuned-sst-2-english", truncation=True)

# STEP 7: Prevedi e valuta
pred_labels = []
true_labels = []

for example in tqdm(subset):
    statement = example["statement"]
    true_label = example["label"]

    prediction = clf(statement)[0]['label']  # LABEL_0 o LABEL_1
    pred = 0 if prediction == "NEGATIVE" else 5  # Mappatura grezza

    pred_labels.append(pred)
    true_labels.append(true_label)

# STEP 8: Calcola accuratezza
acc = accuracy_score(true_labels, pred_labels)
print(f"Accuratezza LLM distillato su 500 esempi: {acc:.2f}")

# STEP 4: Seleziona un sottoinsieme
subset = dataset["test"].select(range(500))  # puoi aumentare il range se vuoi

# STEP 5: Binarizza le etichette (1 = credibile, 0 = non credibile)
def binarize_label(label):
    return 1 if label in [4, 5] else 0

# STEP 6: Pipeline con LLM distillato (sentiment)
clf = pipeline("text-classification", model="distilbert-base-uncased-finetuned-sst-2-english", truncation=True)

# STEP 7: Inferenzia e valuta
pred_labels = []
true_labels = []

for example in tqdm(subset):
    text = example["statement"]
    true_label = binarize_label(example["label"])

    prediction = clf(text)[0]['label']  # POSITIVE o NEGATIVE
    pred = 1 if prediction == "POSITIVE" else 0

    pred_labels.append(pred)
    true_labels.append(true_label)

# STEP 8: Valuta
acc = accuracy_score(true_labels, pred_labels)
print(f"\n✅ Accuratezza binaria: {acc:.2f}\n")
print(classification_report(true_labels, pred_labels, digits=3))

# STEP 1: Installa librerie (se non già installate)
!pip install -q transformers datasets fsspec==2023.9.2 scikit-learn

# STEP 2: Importa librerie
from datasets import load_dataset
from transformers import pipeline
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score
from tqdm import tqdm
import time

# STEP 3: Carica il dataset LIAR
dataset = load_dataset("ucsbnlp/liar")
subset = dataset["test"].select(range(500))

# STEP 4: Funzione per binarizzare etichette
def binarize_label(label):
    return 1 if label in [4, 5] else 0

# STEP 5: Lista di modelli leggeri
models = [
    "distilbert-base-uncased-finetuned-sst-2-english",
    "distilbert-base-uncased",
    "mrm8488/bert-tiny-finetuned-fake-news",
    "mrm8488/distilroberta-fake-news",
    "prajjwal1/bert-mini",
    "prajjwal1/bert-tiny",
    "google/mobilebert-uncased",
    "sshleifer/tiny-distilroberta-base",
    "microsoft/MiniLM-L12-H384-uncased",
    "microsoft/MiniLM-L6-v2"
]

# STEP 6: Itera su tutti i modelli
for model_name in models:
    print(f"\n🔍 Valutazione modello: {model_name}")

    try:
        clf = pipeline("text-classification", model=model_name, truncation=True)
    except Exception as e:
        print(f"❌ Errore nel caricare il modello {model_name}: {e}")
        continue

    pred_labels = []
    true_labels = []

    start_time = time.time()

    for example in tqdm(subset, leave=False):
        text = example["statement"]
        true_label = binarize_label(example["label"])

        try:
            prediction = clf(text)[0]['label'].upper()
            pred = 1 if "POSITIVE" in prediction or "TRUE" in prediction else 0
        except:
            pred = 0  # fallback
        pred_labels.append(pred)
        true_labels.append(true_label)

    end_time = time.time()
    elapsed = end_time - start_time

    acc = accuracy_score(true_labels, pred_labels)
    prec = precision_score(true_labels, pred_labels, zero_division=0)
    rec = recall_score(true_labels, pred_labels, zero_division=0)
    f1 = f1_score(true_labels, pred_labels, zero_division=0)

    print(f"✅ Accuracy       : {acc:.3f}")
    print(f"✅ Precision     : {prec:.3f}")
    print(f"✅ Recall        : {rec:.3f}")
    print(f"✅ F1 Score      : {f1:.3f}")
    print(f"⏱️ Tempo inferenza: {elapsed:.2f} secondi")

# STEP 1: Installa librerie
!pip install -q transformers datasets scikit-learn fsspec==2023.9.2

# STEP 2: Importa librerie
from datasets import load_dataset
from transformers import pipeline, AutoConfig
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score
from tqdm import tqdm
import time

# STEP 3: Carica dataset
dataset = load_dataset("ucsbnlp/liar")
subset = dataset["test"].select(range(500))

# STEP 4: Funzione binarizzazione etichette
def binarize_label(label):
    return 1 if label in [4, 5] else 0

# STEP 5: Modelli leggeri già fine-tuned per classificazione
models = [
    "distilbert-base-uncased-finetuned-sst-2-english", # sentiment
    "mrm8488/bert-tiny-finetuned-fake-news",           # fake news
    "mrm8488/distilroberta-finetuned-fake-news",       # fake news
    "textattack/roberta-base-imdb",                    # sentiment
    "textattack/distilbert-base-uncased-imdb",         # sentiment
    "lvwerra/distilbert-imdb",                         # sentiment
    "cardiffnlp/twitter-roberta-base-sentiment-latest" # sentiment twitter
]

# STEP 6: Valutazione
for model_name in models:
    print(f"\n🔍 Valutazione modello: {model_name}")

    try:
        # Controlla se il modello è fine-tuned per classification
        config = AutoConfig.from_pretrained(model_name)
        if config.architectures and "ForSequenceClassification" not in config.architectures[0]:
            print(f"⚠️ Modello {model_name} non addestrato per classificazione. Skip.")
            continue

        clf = pipeline("text-classification", model=model_name, truncation=True)
    except Exception as e:
        print(f"❌ Errore caricamento {model_name}: {e}")
        continue

    pred_labels = []
    true_labels = []

    start_time = time.time()

    for example in tqdm(subset, leave=False):
        text = example["statement"]
        true_label = binarize_label(example["label"])

        prediction = clf(text)[0]['label'].lower()
        if any(keyword in prediction for keyword in ["positive", "true", "real"]):
            pred = 1
        else:
            pred = 0

        pred_labels.append(pred)
        true_labels.append(true_label)

    end_time = time.time()

    acc = accuracy_score(true_labels, pred_labels)
    prec = precision_score(true_labels, pred_labels, zero_division=0)
    rec = recall_score(true_labels, pred_labels, zero_division=0)
    f1 = f1_score(true_labels, pred_labels, zero_division=0)
    elapsed = end_time - start_time

    print(f"✅ Accuracy       : {acc:.3f}")
    print(f"✅ Precision      : {prec:.3f}")
    print(f"✅ Recall         : {rec:.3f}")
    print(f"✅ F1 Score       : {f1:.3f}")
    print(f"⏱️ Tempo inferenza: {elapsed:.2f} secondi")

# STEP 1: Installa le librerie necessarie
!pip install -q transformers datasets scikit-learn fsspec==2023.9.2

# STEP 2: Importa le librerie
from datasets import load_dataset
from transformers import pipeline, AutoConfig
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score
from tqdm import tqdm
import time

# STEP 3: Carica il dataset
dataset = load_dataset("ucsbnlp/liar")
subset = dataset["test"].select(range(500))

# STEP 4: Funzione per binarizzare le etichette
def binarize_label(label):
    return 1 if label in [4, 5] else 0

# STEP 5: Modelli leggeri già fine-tuned per classificazione
models = [
    "vikram71198/distilroberta-base-finetuned-fake-news-detection",  # fake news
    "Giyaseddin/distilbert-base-cased-finetuned-fake-and-real-news-dataset",  # fake news
    "distilbert-base-uncased-finetuned-sst-2-english",  # sentiment
    "textattack/roberta-base-imdb",  # sentiment
    "textattack/distilbert-base-uncased-imdb",  # sentiment
    "lvwerra/distilbert-imdb",  # sentiment
    "cardiffnlp/twitter-roberta-base-sentiment-latest"  # sentiment twitter
]

# STEP 6: Valutazione dei modelli
for model_name in models:
    print(f"\n🔍 Valutazione modello: {model_name}")

    try:
        # Controlla se il modello è fine-tuned per la classificazione
        config = AutoConfig.from_pretrained(model_name)
        if config.architectures and "ForSequenceClassification" not in config.architectures[0]:
            print(f"⚠️ Modello {model_name} non addestrato per classificazione. Skip.")
            continue

        clf = pipeline("text-classification", model=model_name, truncation=True)
    except Exception as e:
        print(f"❌ Errore caricamento {model_name}: {e}")
        continue

    pred_labels = []
    true_labels = []

    start_time = time.time()

    for example in tqdm(subset, leave=False):
        text = example["statement"]
        true_label = binarize_label(example["label"])

        prediction = clf(text)[0]['label'].lower()
        if any(keyword in prediction for keyword in ["positive", "true", "real", "not_fake_news", "label_1"]):
            pred = 1
        else:
            pred = 0

        pred_labels.append(pred)
        true_labels.append(true_label)

    end_time = time.time()

    acc = accuracy_score(true_labels, pred_labels)
    prec = precision_score(true_labels, pred_labels, zero_division=0)
    rec = recall_score(true_labels, pred_labels, zero_division=0)
    f1 = f1_score(true_labels, pred_labels, zero_division=0)
    elapsed = end_time - start_time

    print(f"✅ Accuracy       : {acc:.3f}")
    print(f"✅ Precision      : {prec:.3f}")
    print(f"✅ Recall         : {rec:.3f}")
    print(f"✅ F1 Score       : {f1:.3f}")
    print(f"⏱️ Tempo inferenza: {elapsed:.2f} secondi")

# STEP 1: Installa le librerie necessarie
!pip install -q transformers datasets scikit-learn fsspec==2023.9.2

# STEP 2: Importa le librerie
from datasets import load_dataset
from transformers import pipeline, AutoConfig
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score
from tqdm import tqdm
import time

# STEP 3: Carica il dataset
dataset = load_dataset("ucsbnlp/liar")
subset = dataset["test"].select(range(500))

# STEP 4: Funzione per binarizzare le etichette
def binarize_label(label):
    return 1 if label in [4, 5] else 0

# STEP 5: Modelli selezionati per la valutazione
models = [
    "microsoft/deberta-v3-base",  # modello avanzato per classificazione
    "roberta-large-mnli",         # modello robusto per inferenza NLI
    "bert-base-uncased",          # modello base per benchmarking
    "facebook/bart-large-mnli",   # modello potente per NLI
    "distilbert-base-uncased-finetuned-sst-2-english"  # modello leggero per sentiment analysis
]

# STEP 6: Valutazione dei modelli
for model_name in models:
    print(f"\n🔍 Valutazione modello: {model_name}")

    try:
        # Controlla se il modello è fine-tuned per la classificazione
        config = AutoConfig.from_pretrained(model_name)
        if config.architectures and "ForSequenceClassification" not in config.architectures[0]:
            print(f"⚠️ Modello {model_name} non addestrato per classificazione. Skip.")
            continue

        clf = pipeline("text-classification", model=model_name, truncation=True)
    except Exception as e:
        print(f"❌ Errore caricamento {model_name}: {e}")
        continue

    pred_labels = []
    true_labels = []

    start_time = time.time()

    for example in tqdm(subset, leave=False):
        text = example["statement"]
        true_label = binarize_label(example["label"])

        prediction = clf(text)[0]['label'].lower()
        if any(keyword in prediction for keyword in ["positive", "true", "real", "entailment", "label_1"]):
            pred = 1
        else:
            pred = 0

        pred_labels.append(pred)
        true_labels.append(true_label)

    end_time = time.time()

    acc = accuracy_score(true_labels, pred_labels)
    prec = precision_score(true_labels, pred_labels, zero_division=0)
    rec = recall_score(true_labels, pred_labels, zero_division=0)
    f1 = f1_score(true_labels, pred_labels, zero_division=0)
    elapsed = end_time - start_time

    print(f"✅ Accuracy       : {acc:.3f}")
    print(f"✅ Precision      : {prec:.3f}")
    print(f"✅ Recall         : {rec:.3f}")
    print(f"✅ F1 Score       : {f1:.3f}")
    print(f"⏱️ Tempo inferenza: {elapsed:.2f} secondi")