# -*- coding: utf-8 -*-
"""Untitled

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1D9YFVz2f1643E2K3XcOOVkra5_FqPNki
"""

#!/usr/bin/env python3
# kpi_by_post.py
import pandas as pd
import numpy as np
from pathlib import Path

# ---------------------------------------------------------------------------
# 1) Elenco dei file da analizzare (stessa cartella dello script)
# ---------------------------------------------------------------------------
FILES = [
    "combined_dataset.csv",
    "putinmissing-all-rnr-threads_rumours.csv",
    "charliehebdo-all-rnr-threads_rumours.csv"
]

# ---------------------------------------------------------------------------
# 2) Sinonimi per auto-detect colonne
# ---------------------------------------------------------------------------
CANDIDATES = {
    "post_id": [
        "tweet_id", "id", "post_id", "conversation_id",
        "thread_id", "postid"
    ],
    "user_id": [
        "user_id", "userid", "author_id", "user",
        "UserId"
    ],
    "timestamp": [
        "created_at", "commentat", "datetime",
        "timestamp", "date", "time"
    ],
    "reactions": [
        "favorite_count", "likes", "reactionscount",
        "like_count", "share_count", "shares",
        "ReactionsCount"
    ],
    "replies": [
        "reply_count", "replies", "comment_count",
        "SubCommentsCount"
    ],
}

def find_col(cols, options):
    """Restituisce il primo nome presente in cols tra le opzioni."""
    cols_lc = {c.lower(): c for c in cols}
    for opt in options:
        if opt.lower() in cols_lc:
            return cols_lc[opt.lower()]
    return None

# ---------------------------------------------------------------------------
# 3) KPI per un singolo groupby(post_id)
# ---------------------------------------------------------------------------
def kpis_for_group(df: pd.DataFrame) -> dict:
    df["timestamp"] = pd.to_datetime(df["timestamp"], errors="coerce")

    for c in ("reactions", "replies"):
        df[c] = pd.to_numeric(df[c], errors="coerce").fillna(0)

    df["views"] = df["reactions"] + df["replies"]

    df_sorted  = df.sort_values("timestamp")
    start_time = df_sorted["timestamp"].min()
    end_time   = df_sorted["timestamp"].max()

    unique_reach = df["user_id"].nunique()
    total_views  = df["views"].sum()

    # Time to initial spread (primo record con ≥10 visualizzazioni)
    spread_row = df_sorted[df_sorted["views"] >= 10].head(1)
    t_init = (
        (spread_row["timestamp"].iloc[0] - start_time).total_seconds() / 60
        if not spread_row.empty and pd.notna(start_time) else np.nan
    )

    lifespan = (
        (end_time - start_time).total_seconds() / 60
        if pd.notna(end_time) and pd.notna(start_time) else np.nan
    )
    grow_rate = (
        total_views / lifespan if lifespan and lifespan > 0 else np.nan
    )

    return dict(
        unique_reach              = unique_reach,
        views                     = total_views,
        time_to_initial_spread_min= t_init,
        content_lifespan_min      = lifespan,
        grow_rate_tweets_per_min  = grow_rate
    )

# ---------------------------------------------------------------------------
# 4) Elaborazione di tutti i file
# ---------------------------------------------------------------------------
all_kpi_rows = []

for file_name in FILES:
    path = Path(file_name)
    if not path.exists():
        print(f"⚠️  File non trovato: {file_name}")
        continue

    raw = pd.read_csv(path)
    mapping = {}

    # auto-detect
    for logical, opts in CANDIDATES.items():
        col = find_col(raw.columns, opts)
        if col:
            mapping[logical] = col

    mandatory = ("post_id", "user_id", "timestamp")
    if not all(m in mapping for m in mandatory):
        print(f"❌  Colonne fondamentali mancanti in {file_name}. Saltato.")
        continue

    # reactions / replies obbligatorie (zero se assenti)
    if "reactions" not in mapping:
        raw["reactions"] = 0
        mapping["reactions"] = "reactions"
    if "replies" not in mapping:
        raw["replies"] = 0
        mapping["replies"] = "replies"

    # dataframe uniformato
    df = raw.rename(columns={
        mapping["post_id"]  : "post_id",
        mapping["user_id"]  : "user_id",
        mapping["timestamp"]: "timestamp",
        mapping["reactions"]: "reactions",
        mapping["replies"]  : "replies"
    })[["post_id", "user_id", "timestamp", "reactions", "replies"]].copy()

    # salva versione pulita
    clean_name = f"clean_{path.stem}.csv"
    df.to_csv(clean_name, index=False)
    print(f"✅ Salvato {clean_name}")

    # KPI per ogni post_id
    for post_id, grp in df.groupby("post_id"):
        kpi_vals = kpis_for_group(grp)
        kpi_vals.update(dataset=path.stem, post_id=post_id)
        all_kpi_rows.append(kpi_vals)

# ---------------------------------------------------------------------------
# 5) Output finale
# ---------------------------------------------------------------------------
out_df = pd.DataFrame(all_kpi_rows)[[
    "dataset",
    "post_id",
    "unique_reach",
    "views",
    "time_to_initial_spread_min",
    "content_lifespan_min",
    "grow_rate_tweets_per_min"
]]

out_df.to_csv("kpi_by_post.csv", index=False)
print("✅ KPI per post salvati in kpi_by_post.csv")

#!/usr/bin/env python3
"""
Publication-ready KPI comparison
================================
This script loads raw KPI data for different online discussions, removes outliers,
computes the mean KPI value **per dataset**, and produces publication-quality
violin plots to compare the full distributions of each KPI side-by-side.

Input files (CSV) must be present in the same directory as the script:
    • kpi_putinmissing.csv
    • kpi_charliehebdo.csv

The script saves one PNG file per KPI (300 dpi) and a CSV file containing the mean
values after outlier removal.

Usage
-----
$ python kpi_publication_analysis.py

Dependencies
------------
Python ≥3.9 and the libraries pandas, seaborn and matplotlib.
Install with:
    pip install pandas seaborn matplotlib
"""
from __future__ import annotations

from pathlib import Path
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

# ----------------------------------------------------------------------------
# Configuration — edit here if you add datasets or KPI columns
# ----------------------------------------------------------------------------
DATASET_FILES: dict[str, str] = {
    "Putin Missing": "kpi_putinmissing.csv",
    "Charlie Hebdo": "kpi_charliehebdo.csv",
}
# KPI columns to analyse (must exist in every CSV)
KPI_COLUMNS: list[str] = [
    "unique_reach",
    "views",
    "time_to_initial_spread_min",
    "content_lifespan_min",
    "grow_rate_tweets_per_min",
]
OUTPUT_DIR = Path("figures")  # where to save PNGs and the summary CSV
OUTPUT_DIR.mkdir(exist_ok=True)

# ----------------------------------------------------------------------------
# Helper functions
# ----------------------------------------------------------------------------

def remove_outliers_iqr(df: pd.DataFrame, column: str) -> pd.DataFrame:
    """Return *df* with values outside 1.5·IQR for *column* filtered out."""
    q1 = df[column].quantile(0.25)
    q3 = df[column].quantile(0.75)
    iqr = q3 - q1
    lower = q1 - 1.5 * iqr
    upper = q3 + 1.5 * iqr
    return df[(df[column] >= lower) & (df[column] <= upper)]


# ----------------------------------------------------------------------------
# Load and concatenate datasets, keeping a label column
# ----------------------------------------------------------------------------
frames: list[pd.DataFrame] = []
for label, filename in DATASET_FILES.items():
    df = pd.read_csv(filename)
    df["dataset"] = label
    frames.append(df)
raw_data = pd.concat(frames, ignore_index=True)

# ----------------------------------------------------------------------------
# Clean data: remove outliers in each KPI *within each dataset*.
# ----------------------------------------------------------------------------
filtered_frames: list[pd.DataFrame] = []
for label, group in raw_data.groupby("dataset"):
    cleaned = group.copy()
    for col in KPI_COLUMNS:
        cleaned = remove_outliers_iqr(cleaned, col)
    filtered_frames.append(cleaned)
clean_data = pd.concat(filtered_frames, ignore_index=True)

# ----------------------------------------------------------------------------
# Compute mean KPI values after cleaning and export as CSV.
# ----------------------------------------------------------------------------
mean_table = (
    clean_data.groupby("dataset")[KPI_COLUMNS]
    .mean()
    .round(3)
    .T  # easier to read with KPIs as rows
)
mean_table.to_csv(OUTPUT_DIR / "mean_metrics_by_dataset.csv")

# ----------------------------------------------------------------------------
# Plot distribution comparison for each KPI.
# ----------------------------------------------------------------------------
sns.set_theme(style="whitegrid", context="talk", font_scale=1.1)
for col in KPI_COLUMNS:
    plt.figure(figsize=(6, 4))
    # Violin for the global shape + swarm for the underlying points
    sns.violinplot(x="dataset", y=col, data=clean_data, inner="quartile", cut=0)
    sns.swarmplot(x="dataset", y=col, data=clean_data, color="k", size=3, alpha=0.4)
    plt.title(col.replace("_", " ").title())
    plt.xlabel("")
    plt.tight_layout()
    plt.savefig(OUTPUT_DIR / f"distribution_{col}.png", dpi=300)
    plt.close()

print("📈 Finished. Figures and summary CSV saved to", OUTPUT_DIR.resolve())

import pandas as pd

# Carica i dati
charlie = pd.read_csv("kpi_charliehebdo.csv")
putin = pd.read_csv("kpi_putinmissing.csv")

# Aggiungi colonna evento
charlie['event'] = 'Charlie Hebdo'
putin['event'] = 'Putin Missing'

# Unisci i due dataframe
df = pd.concat([charlie, putin])

# KPI da confrontare
kpi_columns = [
    'unique_reach',
    'views',
    'time_to_initial_spread_min',
    'content_lifespan_min',
    'grow_rate_tweets_per_min'
]

# Calcola media e std per ciascun KPI per evento
summary = df.groupby('event')[kpi_columns].agg(['mean', 'std'])

# Costruisci LaTeX
latex_table = "\\begin{table}[h!]\n\\centering\n\\begin{tabular}{l" + "c" * len(kpi_columns) + "}\n"
latex_table += "\\toprule\n"
latex_table += "Event & " + " & ".join(kpi.replace('_', ' ').title() for kpi in kpi_columns) + " \\\\\n"
latex_table += "\\midrule\n"

for event in summary.index:
    row = [event]
    for kpi in kpi_columns:
        mean = summary.loc[event][(kpi, 'mean')]
        std = summary.loc[event][(kpi, 'std')]
        cell = f"${mean:.2f} \\pm {std:.2f}$"
        row.append(cell)
    latex_table += " & ".join(row) + " \\\\\n"

latex_table += "\\bottomrule\n\\end{tabular}\n"
latex_table += "\\caption{Propagation Dynamics KPIs for the two case studies.}\n"
latex_table += "\\label{tab:kpi_comparison}\n\\end{table}"

# Stampa LaTeX
print(latex_table)

#!/usr/bin/env python3
"""
KPI Comparison – variante “raw vs mean”
======================================
Confronta i tre dataset KPI (Putin Missing, Charlie Hebdo, Deepfake) e, quando
esistono colonne aggregate con suffisso `_mean`, le include **come KPI a parte**
così che, ad esempio, il grafico di `content_lifespan_min_mean` appaia subito
a fianco di quello di `content_lifespan_min`.

Flusso di lavoro:
1. **Caricamento** dei tre CSV.
2. **Normalizzazione nomi** (minuscolo, rimozione spazi) ma **non** si elimina
   il suffisso `_mean`; le varianti `grow_rate_views_per_min` e
   `grow_rate_tweets_per_min` confluiscono in `grow_rate_per_min` (e la variante
   `_mean` corrispondente).
3. KPI selezionati se presenti in **almeno un dataset** (abbiamo tolto il vincolo
   “≥2 dataset” per consentire le metriche che esistono solo come media).
4. **Rimozione outlier** (1,5·IQR) *per ogni (dataset, KPI)* disponibile.
5. **Tabella medie** (`mean_metrics_by_dataset.csv`) completa di tutte le metriche.
6. **Grafici violin+swarm** per ogni KPI; se una metrica esiste in un solo
   dataset, il grafico mostra comunque quell’unica distribuzione (utile per le
   colonne `_mean`). Su ogni plot sono sovrapposte le medie (rombo rosso).

Uso rapido
-----------
```bash
pip install pandas seaborn matplotlib
python kpi_publication_analysis.py
```

Gli output sono salvati nella cartella `figures/`.
"""
from __future__ import annotations

from pathlib import Path
import re
from collections import Counter
from typing import Dict, Set

import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

# ---------------------------------------------------------------------------
# Config – file sorgente
# ---------------------------------------------------------------------------
DATASET_FILES: Dict[str, str] = {
    "Putin Missing": "kpi_putinmissing.csv",
    "Charlie Hebdo": "kpi_charliehebdo.csv",
    "Deepfake": "kpi_deepfake.csv",
}
OUTPUT_DIR = Path("figures")
OUTPUT_DIR.mkdir(exist_ok=True)

# ---------------------------------------------------------------------------
# Helper – normalizza ma conserva _mean
# ---------------------------------------------------------------------------
_grow_rate_full_re = re.compile(r"grow_rate_(views|tweets)_per_min(_mean)?$", re.IGNORECASE)


def canonical(col: str) -> str:
    col = col.strip().lower().replace(" ", "")
    # uniforma grow_rate_* to grow_rate_per_min (aggiungendo _mean se presente)
    m = _grow_rate_full_re.match(col)
    if m:
        return "grow_rate_per_min" + ("_mean" if m.group(2) else "")
    return col  # lascia tutto il resto intatto (incl. _mean)


# ---------------------------------------------------------------------------
# Carica dataset e normalizza
# ---------------------------------------------------------------------------
frames = []
cols_by_dataset: Dict[str, Set[str]] = {}

for label, csv_path in DATASET_FILES.items():
    df = pd.read_csv(csv_path)
    numeric = df.select_dtypes("number").columns
    rename_map = {c: canonical(c) for c in numeric}
    df = df.rename(columns=rename_map)
    df["dataset"] = label
    frames.append(df)
    cols_by_dataset[label] = set(rename_map.values())

# ---------------------------------------------------------------------------
# Elenco KPI (anche se presenti in un solo dataset)
# ---------------------------------------------------------------------------
KPI_COLUMNS = sorted(set().union(*cols_by_dataset.values()))
print("➡️ KPI totali (raw + mean):", ", ".join(KPI_COLUMNS))

raw_data = pd.concat(frames, ignore_index=True)

# ---------------------------------------------------------------------------
# Outlier cleaning
# ---------------------------------------------------------------------------

def keep_mask(series: pd.Series) -> pd.Series:
    if series.dropna().empty:
        return pd.Series([True] * len(series))
    q1, q3 = series.quantile([0.25, 0.75])
    iqr = q3 - q1
    lower, upper = q1 - 1.5 * iqr, q3 + 1.5 * iqr
    return (series >= lower) & (series <= upper)


clean_frames = []
for label, grp in raw_data.groupby("dataset"):
    cleaned = grp.copy()
    for col in KPI_COLUMNS:
        if col in cleaned:
            mask = keep_mask(cleaned[col])
            cleaned = cleaned[mask | cleaned[col].isna()]
    clean_frames.append(cleaned)
clean_data = pd.concat(clean_frames, ignore_index=True)

# ---------------------------------------------------------------------------
# Tabella medie (wide)
# ---------------------------------------------------------------------------
mean_table = (
    clean_data.melt(id_vars=["dataset"], value_vars=KPI_COLUMNS, var_name="kpi", value_name="value")
    .dropna(subset=["value"])
    .groupby(["kpi", "dataset"])["value"].mean()
    .unstack("dataset")
    .round(3)
    .sort_index()
)
mean_table.to_csv(OUTPUT_DIR / "mean_metrics_by_dataset.csv")

# ---------------------------------------------------------------------------
# Grafici
# ---------------------------------------------------------------------------
print("📊 Creazione violin plot …")
sns.set_theme(style="whitegrid", context="talk", font_scale=1.1)
for col in KPI_COLUMNS:
    subset = clean_data[["dataset", col]].dropna()
    plt.figure(figsize=(7, 4.8))
    sns.violinplot(x="dataset", y=col, data=subset, inner="quartile", cut=0)
    sns.swarmplot(x="dataset", y=col, data=subset, color="k", size=3, alpha=0.4)

    # Overlay della media
    means = subset.groupby("dataset")[col].mean()
    sns.pointplot(x=means.index, y=means.values, join=False, markers="d", scale=1.4, color="firebrick")

    plt.title(col.replace("_", " ").title())
    plt.xlabel("")
    plt.tight_layout()
    out_file = OUTPUT_DIR / f"distribution_{col}.png"
    plt.savefig(out_file, dpi=300)
    plt.close()
    print("  ✔", out_file.name)

print("✅ Tutto pronto! Grafici e tabella in", OUTPUT_DIR.resolve())

import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

# Carica i dati
charlie = pd.read_csv("kpi_charliehebdo.csv")
putin = pd.read_csv("kpi_putinmissing.csv")

# Aggiunge label evento
charlie['event'] = 'Charlie Hebdo'
putin['event'] = 'Putin Missing'

# Unisci
df = pd.concat([charlie, putin])

# Rimuove valori negativi (non validi)
df = df[
    (df['time_to_initial_spread_min'] >= 0) &
    (df['content_lifespan_min'] >= 0)
]

# KPI da tracciare
kpi_columns = [
    'unique_reach',
    'views',
    'time_to_initial_spread_min',
    'content_lifespan_min',
    'grow_rate_tweets_per_min'
]

# Colori distinti
colors = ['#1f77b4', '#ff7f0e', '#2ca02c', '#d62728', '#9467bd']

# Rimuove outlier per ogni KPI e per ciascun evento
def remove_outliers(group, column):
    q1 = group[column].quantile(0.25)
    q3 = group[column].quantile(0.75)
    iqr = q3 - q1
    lower = q1 - 1.5 * iqr
    upper = q3 + 1.5 * iqr
    return group[(group[column] >= lower) & (group[column] <= upper)]

# Crea figura e griglia 3x2
fig, axes = plt.subplots(nrows=3, ncols=2, figsize=(14, 12))
axes = axes.flatten()

# Plot KPI senza outlier e senza barre d’errore
for i, kpi in enumerate(kpi_columns):
    ax = axes[i]
    means = []
    labels = []

    for event in ['Charlie Hebdo', 'Putin Missing']:
        subset = df[df['event'] == event]
        cleaned = remove_outliers(subset, kpi)
        mean_val = cleaned[kpi].mean()
        means.append(mean_val)
        labels.append(event)

    ax.bar(labels, means, color=colors[i])
    ax.set_title(kpi.replace('_', ' ').title(), fontsize=12)
    ax.set_ylabel('')
    ax.grid(True, axis='y', linestyle='--', alpha=0.5)

    for j, value in enumerate(means):
        ax.text(j, value + 0.5, f'{value:.1f}', ha='center', fontsize=10)

# Nasconde subplot vuoto
if len(kpi_columns) < len(axes):
    fig.delaxes(axes[-1])

# Titolo globale
fig.suptitle('KPI medi (senza outlier): Charlie Hebdo vs Putin Missing', fontsize=16)
plt.tight_layout(rect=[0, 0.03, 1, 0.95])

# Salvataggio
plt.savefig("kpi_confronto_no_outliers.png", dpi=300)
plt.show()

import pandas as pd
import matplotlib.pyplot as plt

# Carica i dati
charlie = pd.read_csv("kpi_charliehebdo.csv")
putin = pd.read_csv("kpi_putinmissing.csv")

# Aggiunge label evento
charlie['event'] = 'Charlie Hebdo'
putin['event'] = 'Putin Missing'

# Unisce i dataset
df = pd.concat([charlie, putin])

# Rimuove valori negativi non validi
df = df[
    (df['time_to_initial_spread_min'] >= 0) &
    (df['content_lifespan_min'] >= 0)
]

# KPI da tracciare
kpi_columns = [
    'unique_reach',
    'views',
    'time_to_initial_spread_min',
    'content_lifespan_min',
    'grow_rate_tweets_per_min'
]

# === 1. BOXPLOT (Distribuzioni) ===
fig, axes = plt.subplots(nrows=3, ncols=2, figsize=(14, 12))
axes = axes.flatten()

for i, kpi in enumerate(kpi_columns):
    ax = axes[i]
    df.boxplot(column=kpi, by='event', ax=ax, grid=True)
    ax.set_title(kpi.replace('_', ' ').title(), fontsize=12)
    ax.set_xlabel('')
    ax.set_ylabel('')
    ax.grid(True, axis='y', linestyle='--', alpha=0.5)

# Rimuove titolo automatico
fig.suptitle('Distribution of KPIs per Event (with Outliers)', fontsize=16)
plt.tight_layout(rect=[0, 0.03, 1, 0.95])
plt.show()

# === 2. TABELLA LATEX (Medie) ===
mean_table = df.groupby('event')[kpi_columns].mean().round(2)

latex_table = mean_table.reset_index().to_latex(
    index=False,
    caption="Mean KPI values per event (with outliers)",
    label="tab:kpi_means",
    column_format="lrrrrr",
    escape=False
)

print(latex_table)

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.cluster import KMeans
from sklearn.preprocessing import StandardScaler

# === PARAMETRI ===
charlie_file = "charliehebdo-all-rnr-threads_rumours.csv"
putin_file = "putinmissing-all-rnr-threads_rumours.csv"
n_clusters = 4

# === NOMI CLUSTER ===
cluster_names = {
    0: "Balanced Commenters",
    1: "High-Frequency Posters",
    2: "Analytical Writers",
    3: "Emphatic Reactors"
}

# === FUNZIONI ===

def extract_user_features(df):
    df['created_at'] = pd.to_datetime(df['created_at'], errors='coerce')
    user_groups = df.groupby('user_id')
    rows = []

    for user_id, group in user_groups:
        texts = group['text'].dropna().tolist()
        full_text = ' '.join(texts)
        words = full_text.split()
        n_words = len(words)
        n_unique = len(set(words))

        avg_word_len = np.mean([len(w) for w in words]) if words else 0
        punct_density = sum(1 for c in full_text if c in '.,;:!?') / len(full_text) if full_text else 0
        caps_ratio = sum(1 for c in full_text if c.isupper()) / len(full_text) if full_text else 0
        tweet_rate = len(group) / ((group['created_at'].max() - group['created_at'].min()).total_seconds() / 3600 + 1)
        ttr = n_unique / n_words if n_words else 0

        rows.append({
            'user_id': user_id,
            'avg_word_len': avg_word_len,
            'punct_density': punct_density,
            'caps_ratio': caps_ratio,
            'tweet_rate': tweet_rate,
            'type_token_ratio': ttr
        })

    return pd.DataFrame(rows)

def cluster_users(user_features, k):
    X = user_features.drop(columns=['user_id'])
    X_scaled = StandardScaler().fit_transform(X)
    kmeans = KMeans(n_clusters=k, random_state=42)
    user_features['cluster'] = kmeans.fit_predict(X_scaled)
    return user_features

def process_event(file_path, k):
    df = pd.read_csv(file_path, parse_dates=['created_at'])
    df = df[df['tweet_type'] == 'reaction']
    user_features = extract_user_features(df)
    user_clusters = cluster_users(user_features, k)
    user_clusters['cluster_name'] = user_clusters['cluster'].map(cluster_names)
    df = df.merge(user_clusters[['user_id', 'cluster_name']], on='user_id', how='left')
    return df

# === ESECUZIONE ===

charlie_df = process_event(charlie_file, n_clusters)
putin_df = process_event(putin_file, n_clusters)

# === PLOT GRAFICI ===

charlie_counts = charlie_df['cluster_name'].value_counts().reindex(cluster_names.values())
putin_counts = putin_df['cluster_name'].value_counts().reindex(cluster_names.values())

fig, axes = plt.subplots(1, 2, figsize=(16, 6))

axes[0].bar(charlie_counts.index, charlie_counts.values, color='skyblue')
axes[0].set_title("User Distribution per Cluster – Charlie Hebdo")
axes[0].set_xlabel("Cluster")
axes[0].set_ylabel("Number of Users")
axes[0].tick_params(axis='x', rotation=20)

axes[1].bar(putin_counts.index, putin_counts.values, color='salmon')
axes[1].set_title("User Distribution per Cluster – Putin Missing")
axes[1].set_xlabel("Cluster")
axes[1].set_ylabel("Number of Users")
axes[1].tick_params(axis='x', rotation=20)

plt.tight_layout()
plt.show()

import pandas as pd
import matplotlib.pyplot as plt

# === Carica i dati Charlie Hebdo e Putin Missing ===
charlie = pd.read_csv("kpi_charliehebdo.csv")
putin = pd.read_csv("kpi_putinmissing.csv")

charlie['event'] = 'Charlie Hebdo'
putin['event'] = 'Putin Missing'

# === Crea il DataFrame per DeepFake ===
deepfake_data = {
    'unique_reach': [200.0, 203.0, 204.0, 66.0, 199.0, 164.0, 36.0, 68.0, 59.0],
    'views': [1339.0, 2682.0, 1061.0, 134.0, 605.0, 361.0, 87.0, 145.0, 99.0],
    'comments_replies': [254.0, 166.0, 128.0, 50.0, 187.0, 31.0, 61.0, 6.0, 25.0],
    'time_to_initial_spread_min': [0.0, 45.55, 0.0, 3.05, 0.0, 4.08, 69.13, 2.75, 0.0],
    'content_lifespan_min': [9672.28, 3820745.71, 467053.91, 2743395.03, 11862.53, 21968.06, 8318.5, 211380.85, 7109.3],
    'grow_rate_tweets_per_min': [0.1384, 0.0007, 0.0023, 0.00005, 0.0510, 0.0164, 0.0105, 0.0007, 0.0139],
}
deepfake_df = pd.DataFrame(deepfake_data)
deepfake_df['event'] = 'DeepFake'

# === Unione dei dataset ===
df = pd.concat([charlie, putin, deepfake_df], ignore_index=True)

# Rimuove valori negativi non validi
df = df[
    (df['time_to_initial_spread_min'] >= 0) &
    (df['content_lifespan_min'] >= 0)
]

# === KPI da tracciare ===
kpi_columns = [
    'unique_reach',
    'views',
    'time_to_initial_spread_min',
    'content_lifespan_min',
    'grow_rate_tweets_per_min'
]

# === 1. BOXPLOT ===
fig, axes = plt.subplots(nrows=3, ncols=2, figsize=(14, 12))
axes = axes.flatten()

for i, kpi in enumerate(kpi_columns):
    ax = axes[i]
    df.boxplot(column=kpi, by='event', ax=ax, grid=True)
    ax.set_title(kpi.replace('_', ' ').title(), fontsize=12)
    ax.set_xlabel('')
    ax.set_ylabel('')
    ax.grid(True, axis='y', linestyle='--', alpha=0.5)

fig.suptitle('Distribution of KPIs per Event (with Outliers)', fontsize=16)
plt.tight_layout(rect=[0, 0.03, 1, 0.95])
plt.show()

# === 2. TABELLA LATEX ===
mean_table = df.groupby('event')[kpi_columns].mean().round(2)

latex_table = mean_table.reset_index().to_latex(
    index=False,
    caption="Mean KPI values per event (with outliers)",
    label="tab:kpi_means",
    column_format="lrrrrr",
    escape=False
)

print(latex_table)

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.cluster import KMeans
from sklearn.preprocessing import StandardScaler

# === PARAMETRI ===
input_file = "alldata.csv"
n_clusters = 4

# === NOMI CLUSTER IMPOSTATI ===
cluster_names = {
    0: "Balanced Commenters",
    1: "High-Frequency Posters",
    2: "Analytical Writers",
    3: "Emphatic Reactors"
}

# === FUNZIONI ===

def extract_comment_features(df):
    rows = []

    for idx, row in df.iterrows():
        text = str(row['Content'])
        words = text.split()
        n_words = len(words)
        n_unique = len(set(words))

        avg_word_len = np.mean([len(w) for w in words]) if words else 0
        punct_density = sum(1 for c in text if c in '.,;:!?') / len(text) if text else 0
        caps_ratio = sum(1 for c in text if c.isupper()) / len(text) if text else 0
        ttr = n_unique / n_words if n_words else 0
        reactions = row.get('ReactionsCount', 0)

        rows.append({
            'id_commento': row['id_commento'],
            'avg_word_len': avg_word_len,
            'punct_density': punct_density,
            'caps_ratio': caps_ratio,
            'type_token_ratio': ttr,
            'ReactionsCount': reactions
        })

    return pd.DataFrame(rows)

def cluster_comments(comment_features, k):
    X = comment_features.drop(columns=['id_commento'])
    X_scaled = StandardScaler().fit_transform(X)
    kmeans = KMeans(n_clusters=k, random_state=42)
    comment_features['cluster'] = kmeans.fit_predict(X_scaled)
    comment_features['cluster_name'] = comment_features['cluster'].map(cluster_names)
    return comment_features

# === ESECUZIONE ===

df = pd.read_csv(input_file)
comment_features = extract_comment_features(df)
comment_clusters = cluster_comments(comment_features, n_clusters)

# Join per visualizzare
df = df.merge(comment_clusters[['id_commento', 'cluster_name']], on='id_commento', how='left')
counts = df['cluster_name'].value_counts().reindex(cluster_names.values())

# === PLOT ===
plt.figure(figsize=(10, 6))
plt.bar(counts.index, counts.values, color='mediumseagreen')
plt.title("User Distribution per Cluster – DeepFake Cultural Heritage")
plt.xlabel("Cluster")
plt.ylabel("Numero di commenti")
plt.xticks(rotation=20)
plt.tight_layout()
plt.show()

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import StandardScaler
from sklearn.tree import DecisionTreeClassifier, plot_tree
from sklearn.cluster import KMeans

# === CONFIGURAZIONE ===
charlie_path = "charliehebdo-all-rnr-threads_rumours.csv"
putin_path = "putinmissing-all-rnr-threads_rumours.csv"
n_clusters = 4

# === FUNZIONI ===

def extract_user_features(df):
    df['created_at'] = pd.to_datetime(df['created_at'], errors='coerce')
    user_groups = df.groupby('user_id')
    rows = []

    for user_id, group in user_groups:
        texts = group['text'].dropna().tolist()
        full_text = ' '.join(texts)
        words = full_text.split()
        n_words = len(words)
        n_unique = len(set(words))

        avg_word_len = np.mean([len(w) for w in words]) if words else 0
        punct_density = sum(1 for c in full_text if c in '.,;:!?') / len(full_text) if full_text else 0
        caps_ratio = sum(1 for c in full_text if c.isupper()) / len(full_text) if full_text else 0
        tweet_rate = len(group) / ((group['created_at'].max() - group['created_at'].min()).total_seconds() / 3600 + 1)
        ttr = n_unique / n_words if n_words else 0

        rows.append({
            'user_id': user_id,
            'avg_word_len': avg_word_len,
            'punct_density': punct_density,
            'caps_ratio': caps_ratio,
            'tweet_rate': tweet_rate,
            'type_token_ratio': ttr
        })

    return pd.DataFrame(rows)

def cluster_and_explain(df, dataset_name, k=4):
    print(f"\n📊 ANALISI CLUSTER: {dataset_name}")
    df = df[df['tweet_type'] == 'reaction']
    user_features = extract_user_features(df)

    # Clustering
    X = user_features.drop(columns=['user_id'])
    X_scaled = StandardScaler().fit_transform(X)
    km = KMeans(n_clusters=k, random_state=42)
    user_features['cluster'] = km.fit_predict(X_scaled)
    df = df.merge(user_features[['user_id', 'cluster']], on='user_id', how='left')

    # Statistiche riassuntive
    print("\n📈 Statistiche per cluster:")
    print(user_features.groupby('cluster').mean())

    # Boxplot
    for col in X.columns:
        plt.figure(figsize=(8, 4))
        sns.boxplot(data=user_features, x='cluster', y=col)
        plt.title(f"{dataset_name} – Distribuzione {col}")
        plt.tight_layout()
        plt.show()

    # Albero decisionale
    clf = DecisionTreeClassifier(max_depth=3, random_state=0)
    clf.fit(X_scaled, user_features['cluster'])
    plt.figure(figsize=(14, 6))
    plot_tree(clf, feature_names=X.columns, class_names=[f"Cluster {i}" for i in range(k)], filled=True)
    plt.title(f"{dataset_name} – Albero decisionale per spiegare i cluster")
    plt.tight_layout()
    plt.show()

# === ESECUZIONE ===

charlie_df = pd.read_csv(charlie_path, parse_dates=['created_at'])
putin_df = pd.read_csv(putin_path, parse_dates=['created_at'])

cluster_and_explain(charlie_df, "Charlie Hebdo", k=n_clusters)
cluster_and_explain(putin_df, "Putin Missing", k=n_clusters)

import pandas as pd
import numpy as np
import re
from sklearn.preprocessing import StandardScaler
from sklearn.cluster import KMeans
from sklearn.tree import DecisionTreeClassifier, plot_tree
import matplotlib.pyplot as plt

# === FILE PATHS ===
charlie_path = "charliehebdo-all-rnr-threads_rumours.csv"
putin_path = "putinmissing-all-rnr-threads_rumours.csv"
all_data_path = "alldata.csv"

# === CONFIG ===
n_clusters = 4
cluster_names = {
    0: "Balanced Commenters",
    1: "High-Frequency Posters",
    2: "Analytical Writers",
    3: "Emphatic Reactors"
}

# === FEATURE EXTRACTORS ===

def extract_user_features(df):
    df['created_at'] = pd.to_datetime(df['created_at'], errors='coerce')
    user_groups = df.groupby('user_id')
    rows = []

    for user_id, group in user_groups:
        texts = group['text'].dropna().tolist()
        full_text = ' '.join(texts)
        words = full_text.split()
        n_words = len(words)
        n_unique = len(set(words))

        avg_word_len = np.mean([len(w) for w in words]) if words else 0
        punct_density = sum(1 for c in full_text if c in '.,;:!?') / len(full_text) if full_text else 0
        caps_ratio = sum(1 for c in full_text if c.isupper()) / len(full_text) if full_text else 0
        tweet_rate = len(group) / ((group['created_at'].max() - group['created_at'].min()).total_seconds() / 3600 + 1)
        ttr = n_unique / n_words if n_words else 0

        rows.append({
            'avg_word_len': avg_word_len,
            'punct_density': punct_density,
            'caps_ratio': caps_ratio,
            'tweet_rate': tweet_rate,
            'type_token_ratio': ttr
        })

    return pd.DataFrame(rows)

def extract_comment_features(df):
    rows = []

    for _, row in df.iterrows():
        text = str(row['Content'])
        words = re.findall(r'\b\w+\b', text)
        n_words = len(words)
        n_unique = len(set(words))

        avg_word_len = np.mean([len(w) for w in words]) if words else 0
        punct_density = sum(1 for c in text if c in '.,;:!?') / len(text) if text else 0
        caps_ratio = sum(1 for c in text if c.isupper()) / len(text) if text else 0
        ttr = n_unique / n_words if n_words else 0

        rows.append({
            'avg_word_len': avg_word_len,
            'punct_density': punct_density,
            'caps_ratio': caps_ratio,
            'tweet_rate': 0,  # no time info
            'type_token_ratio': ttr
        })

    return pd.DataFrame(rows)

# === LOAD AND PROCESS ===

charlie_df = pd.read_csv(charlie_path)
putin_df = pd.read_csv(putin_path)
alldata_df = pd.read_csv(all_data_path)

charlie_features = extract_user_features(charlie_df[charlie_df['tweet_type'] == 'reaction'])
putin_features = extract_user_features(putin_df[putin_df['tweet_type'] == 'reaction'])
deepfake_features = extract_comment_features(alldata_df)

# === COMBINED CLUSTERING ===

combined = pd.concat([charlie_features, putin_features, deepfake_features], ignore_index=True)
X = combined.fillna(0)
X_scaled = StandardScaler().fit_transform(X)

kmeans = KMeans(n_clusters=n_clusters, random_state=42)
combined['cluster'] = kmeans.fit_predict(X_scaled)

# === DECISION TREE GLOBAL ===

clf = DecisionTreeClassifier(max_depth=3, random_state=0)
clf.fit(X_scaled, combined['cluster'])

# === PLOT ===

plt.figure(figsize=(18, 9))
plot_tree(clf,
          feature_names=X.columns,
          class_names=[cluster_names[i] for i in range(n_clusters)],
          filled=True, rounded=True)
plt.title("Decision Tree – Global Stylometric Cluster Explanation")
plt.tight_layout()
plt.show()

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import re
from sklearn.preprocessing import StandardScaler
from sklearn.cluster import KMeans
from sklearn.tree import DecisionTreeClassifier, plot_tree

# === CONFIG ===
all_data_path = "alldata.csv"
n_clusters = 4
cluster_names = {
    0: "Balanced Commenters",
    1: "High-Frequency Posters",
    2: "Analytical Writers",
    3: "Emphatic Reactors"
}

# === FEATURE EXTRACTION ===
def extract_comment_features(df):
    rows = []

    for _, row in df.iterrows():
        text = str(row['Content'])
        words = re.findall(r'\b\w+\b', text)  # solo parole alfanumeriche
        n_words = len(words)
        n_unique = len(set(words))

        avg_word_len = np.mean([len(w) for w in words]) if words else 0
        punct_density = sum(1 for c in text if c in '.,;:!?') / len(text) if text else 0
        caps_ratio = sum(1 for c in text if c.isupper()) / len(text) if text else 0
        ttr = n_unique / n_words if n_words else 0

        rows.append({
            'id_commento': row['id_commento'],
            'avg_word_len': avg_word_len,
            'punct_density': punct_density,
            'caps_ratio': caps_ratio,
            'type_token_ratio': ttr
        })

    return pd.DataFrame(rows)

# === CLUSTERING E PLOT ===
def cluster_and_plot_all_data(file_path, k=4):
    df = pd.read_csv(file_path)
    features = extract_comment_features(df)

    # Clustering
    X = features.drop(columns=['id_commento'])
    X_scaled = StandardScaler().fit_transform(X)
    km = KMeans(n_clusters=k, random_state=42)
    features['cluster'] = km.fit_predict(X_scaled)
    features['cluster_name'] = features['cluster'].map(cluster_names)

    # Statistiche per cluster
    print("\n📊 Statistiche per cluster:")
    print(features.groupby('cluster_name').mean().round(3))

    # Boxplot per ogni feature
    for col in X.columns:
        plt.figure(figsize=(8, 4))
        sns.boxplot(data=features, x='cluster_name', y=col)
        plt.title(f"Distribuzione {col} per cluster")
        plt.xticks(rotation=20)
        plt.tight_layout()
        plt.show()

    # Albero decisionale
    clf = DecisionTreeClassifier(max_depth=3, random_state=0)
    clf.fit(X_scaled, features['cluster'])
    plt.figure(figsize=(14, 6))
    plot_tree(clf, feature_names=X.columns, class_names=[cluster_names[i] for i in range(k)], filled=True)
    plt.title("Albero decisionale per spiegare i cluster")
    plt.tight_layout()
    plt.show()

# === AVVIO ===
cluster_and_plot_all_data(all_data_path, k=n_clusters)

import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

# === METRICHE PER CHARLIE HEBDO E PUTIN MISSING ===

charlie_stats = {
    0: [5.730571, 0.019759, 0.072191, 1.009691, 0.958301],
    1: [6.168323, 0.020709, 0.074775, 2.965281, 0.681230],
    2: [8.741428, 0.047051, 0.127787, 1.014683, 0.989922],
    3: [6.384219, 0.016617, 0.554019, 1.180480, 0.926675]
}

putin_stats = {
    0: [9.585727, 0.057729, 0.092127, 1.000000, 1.000000],
    1: [5.591657, 0.022124, 0.040675, 0.987235, 0.975807],
    2: [5.899163, 0.024565, 0.056816, 2.087351, 0.816945],
    3: [6.911800, 0.023279, 0.126719, 0.941479, 0.979797]
}

labels = ['avg_word_len', 'punct_density', 'caps_ratio', 'tweet_rate', 'type_token_ratio']
cluster_names = ['Balanced Commenters', 'High-Frequency Posters', 'Analytical Writers', 'Emphatic Reactors']

def plot_radar(data_dict, dataset_name):
    values = [data_dict[k] for k in range(4)]
    num_vars = len(labels)

    # Aggiunge il primo punto in coda per chiudere il cerchio
    angles = np.linspace(0, 2 * np.pi, num_vars, endpoint=False).tolist()
    angles += angles[:1]

    fig, ax = plt.subplots(figsize=(8, 8), subplot_kw=dict(polar=True))

    for i, val in enumerate(values):
        vals = val + [val[0]]  # chiudi il loop
        ax.plot(angles, vals, label=cluster_names[i], linewidth=2)
        ax.fill(angles, vals, alpha=0.1)

    ax.set_title(f"{dataset_name} – Stylometric Profiles", size=16)
    ax.set_xticks(angles[:-1])
    ax.set_xticklabels(labels)
    ax.set_yticklabels([])
    ax.legend(loc='upper right', bbox_to_anchor=(1.3, 1.1))
    plt.tight_layout()
    plt.show()

# === PLOT PER ENTRAMBI I DATASET ===

plot_radar(charlie_stats, "Charlie Hebdo")
plot_radar(putin_stats, "Putin Missing")

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.cluster import KMeans
from sklearn.preprocessing import StandardScaler

# === PARAMETRI ===
charlie_file = "charliehebdo_classified_fast.csv"
putin_file = "putinmissing_classified_fast.csv"
combined_file = "combined_classified_clustered.csv"
n_clusters = 4

# === NOMI CLUSTER ===
cluster_names = {
    0: "Balanced Commenters",
    1: "High-Frequency Posters",
    2: "Analytical Writers",
    3: "Emphatic Reactors"
}

# === FUNZIONI ===

def extract_user_features(df):
    df['created_at'] = pd.to_datetime(df['created_at'], errors='coerce')
    user_groups = df.groupby('user_id')
    rows = []

    for user_id, group in user_groups:
        texts = group['text'].dropna().tolist()
        full_text = ' '.join(texts)
        words = full_text.split()
        n_words = len(words)
        n_unique = len(set(words))

        avg_word_len = np.mean([len(w) for w in words]) if words else 0
        punct_density = sum(1 for c in full_text if c in '.,;:!?') / len(full_text) if full_text else 0
        caps_ratio = sum(1 for c in full_text if c.isupper()) / len(full_text) if full_text else 0
        tweet_rate = len(group) / ((group['created_at'].max() - group['created_at'].min()).total_seconds() / 3600 + 1)
        ttr = n_unique / n_words if n_words else 0

        rows.append({
            'user_id': user_id,
            'avg_word_len': avg_word_len,
            'punct_density': punct_density,
            'caps_ratio': caps_ratio,
            'tweet_rate': tweet_rate,
            'type_token_ratio': ttr
        })

    return pd.DataFrame(rows)

def cluster_users(user_features, k):
    X = user_features.drop(columns=['user_id'])
    X_scaled = StandardScaler().fit_transform(X)
    kmeans = KMeans(n_clusters=k, random_state=42)
    user_features['cluster'] = kmeans.fit_predict(X_scaled)
    return user_features

def process_event(file_path, k):
    df = pd.read_csv(file_path, parse_dates=['created_at'])
    df = df[(df['tweet_type'] == 'reaction') & (df['stance_label'].notna())]
    user_features = extract_user_features(df)
    user_clusters = cluster_users(user_features, k)
    user_clusters['cluster_name'] = user_clusters['cluster'].map(cluster_names)
    df = df.merge(user_clusters[['user_id', 'cluster_name']], on='user_id', how='left')
    return df

def calculate_stance_distribution(df, cluster_column):
    stance_counts = df.groupby(cluster_column)['stance_label'].value_counts(normalize=True).unstack().fillna(0)
    stance_counts = stance_counts[["B", "D", "N"]] * 100
    return stance_counts

def plot_cluster_distribution(stance_df, title, ax):
    labels = stance_df.index.tolist()
    x = np.arange(len(labels))
    width = 0.25

    bars_b = ax.bar(x - width, stance_df["B"], width, label="Belief", color="skyblue")
    bars_d = ax.bar(x, stance_df["D"], width, label="Disbelief", color="salmon")
    bars_n = ax.bar(x + width, stance_df["N"], width, label="Neutral", color="lightgray")

    for bars in [bars_b, bars_d, bars_n]:
        for bar in bars:
            height = bar.get_height()
            ax.annotate(f'{height:.1f}%', xy=(bar.get_x() + bar.get_width() / 2, height),
                        xytext=(0, 3), textcoords="offset points", ha='center', va='bottom', fontsize=8)

    ax.set_title(title)
    ax.set_ylabel("Percentuale")
    ax.set_xticks(x)
    ax.set_xticklabels(labels, rotation=15)
    ax.legend(title="Stance")

# === ESECUZIONE ===

charlie_df = process_event(charlie_file, n_clusters)
charlie_stance = calculate_stance_distribution(charlie_df, cluster_column="cluster_name")

putin_df = process_event(putin_file, n_clusters)
putin_stance = calculate_stance_distribution(putin_df, cluster_column="cluster_name")

combined_df = pd.read_csv(combined_file)
combined_df = combined_df[combined_df["stance_label"].notna()]
combined_stance = calculate_stance_distribution(combined_df, cluster_column="style_cluster_name")

# === PLOT 3 GRAFICI IN COLONNA ===

fig, axes = plt.subplots(3, 1, figsize=(12, 16))

plot_cluster_distribution(charlie_stance, "Stance per Cluster – Charlie Hebdo", axes[0])
plot_cluster_distribution(putin_stance, "Stance per Cluster – Putin Missing", axes[1])
plot_cluster_distribution(combined_stance, "Stance per Style Cluster – Combined", axes[2])

plt.tight_layout()
plt.show()

import pandas as pd
import numpy as np
from sklearn.cluster import KMeans
from sklearn.preprocessing import StandardScaler

# === PARAMETRI ===
input_files = [
    ("combined_classified.csv", "id_commento", "Content"),
    ("charliehebdo_classified_fast.csv", "id", "text"),
    ("putinmissing_classified_fast.csv", "id", "text")
]
n_clusters = 4

# === NOMI CLUSTER ===
cluster_names = {
    0: "Balanced Commenters",
    1: "High-Frequency Posters",
    2: "Analytical Writers",
    3: "Emphatic Reactors"
}

# === FUNZIONI ===

def extract_comment_features(df, id_col, text_col):
    rows = []
    for idx, row in df.iterrows():
        text = str(row[text_col])
        words = text.split()
        n_words = len(words)
        n_unique = len(set(words))

        avg_word_len = np.mean([len(w) for w in words]) if words else 0
        punct_density = sum(1 for c in text if c in '.,;:!?') / len(text) if text else 0
        caps_ratio = sum(1 for c in text if c.isupper()) / len(text) if text else 0
        ttr = n_unique / n_words if n_words else 0

        rows.append({
            id_col: row[id_col],
            'avg_word_len': avg_word_len,
            'punct_density': punct_density,
            'caps_ratio': caps_ratio,
            'type_token_ratio': ttr
        })

    return pd.DataFrame(rows)

def cluster_comments(comment_features, id_col, k):
    X = comment_features.drop(columns=[id_col])
    X_scaled = StandardScaler().fit_transform(X)
    kmeans = KMeans(n_clusters=k, random_state=42)
    comment_features['cluster'] = kmeans.fit_predict(X_scaled)
    comment_features['cluster_name'] = comment_features['cluster'].map(cluster_names)
    return comment_features

# === PROCESSA TUTTI I FILE ===
for file_path, id_col, text_col in input_files:
    print(f"🔄 Elaborazione file: {file_path}")
    df = pd.read_csv(file_path)
    features = extract_comment_features(df, id_col, text_col)
    clusters = cluster_comments(features, id_col, n_clusters)
    df = df.merge(clusters[[id_col, 'cluster_name']], on=id_col, how='left')
    output_path = file_path.replace(".csv", "_with_style_cluster.csv")
    df.to_csv(output_path, index=False)
    print(f"✅ Salvato: {output_path}")

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.cluster import KMeans
from sklearn.preprocessing import StandardScaler

# === PARAMETRI ===
combined_file = "combined_classified.csv"
n_clusters = 4

# === NOMI CLUSTER COERENTI ===
cluster_names = {
    0: "Balanced Commenters",
    1: "High-Frequency Posters",
    2: "Analytical Writers",
    3: "Emphatic Reactors"
}

# === FUNZIONI ===

def extract_stylistic_features_only(df):
    user_groups = df.groupby('user_id')
    rows = []

    for user_id, group in user_groups:
        texts = group['text'].dropna().tolist()
        full_text = ' '.join(texts)
        words = full_text.split()
        n_words = len(words)
        n_unique = len(set(words))

        avg_word_len = np.mean([len(w) for w in words]) if words else 0
        punct_density = sum(1 for c in full_text if c in '.,;:!?') / len(full_text) if full_text else 0
        caps_ratio = sum(1 for c in full_text if c.isupper()) / len(full_text) if full_text else 0
        ttr = n_unique / n_words if n_words else 0

        rows.append({
            'user_id': user_id,
            'avg_word_len': avg_word_len,
            'punct_density': punct_density,
            'caps_ratio': caps_ratio,
            'type_token_ratio': ttr
        })

    return pd.DataFrame(rows)

def cluster_users(user_features, k):
    X = user_features.drop(columns=['user_id'])
    X_scaled = StandardScaler().fit_transform(X)
    kmeans = KMeans(n_clusters=k, random_state=42)
    user_features['cluster'] = kmeans.fit_predict(X_scaled)
    return user_features

# === CARICAMENTO DATI ===
df = pd.read_csv(combined_file)
df = df[df['Content'].notna() & df['user_id'].notna()]

# === CLUSTERING SOLO SU FEATURE STILOMETRICHE ===
user_features = extract_stylistic_features_only(df)
user_clusters = cluster_users(user_features, n_clusters)
user_clusters['cluster_name'] = user_clusters['cluster'].map(cluster_names)

# === MERGE CON I COMMENTI ===
df = df.merge(user_clusters[['user_id', 'cluster_name']], on='user_id', how='left')

# === CALCOLO % STANCE PER CLUSTER ===
stance_dist = df.groupby(['cluster_name', 'stance_label']).size().unstack(fill_value=0)
stance_percent = stance_dist.div(stance_dist.sum(axis=1), axis=0) * 100

# === PLOT ===
stance_percent.plot(kind='bar', stacked=True, figsize=(10, 6), colormap='Set2')
plt.title("Distribuzione % di Credulità (B), Incredulità (D), Neutrale (N) per Cluster")
plt.ylabel("Percentuale")
plt.xlabel("Cluster Stilometrico")
plt.legend(title="Stance", loc="upper right")
plt.xticks(rotation=15)
plt.tight_layout()
plt.show()

import pandas as pd
import numpy as np
from sklearn.cluster import KMeans
from sklearn.preprocessing import StandardScaler

# === PARAMETRI ===
input_file = "combined_classified.csv"
output_file = "combined_classified_clustered_cleaned.csv"
n_clusters = 4

# === NOMI CLUSTER ===
cluster_names = {
    0: "Balanced Commenters",
    1: "High-Frequency Posters",
    2: "Analytical Writers",
    3: "Emphatic Reactors"
}

# === FUNZIONI ===

def extract_comment_features(df):
    rows = []

    for idx, row in df.iterrows():
        text = str(row['Content'])
        words = text.split()
        n_words = len(words)
        n_unique = len(set(words))

        avg_word_len = np.mean([len(w) for w in words]) if words else 0
        punct_density = sum(1 for c in text if c in '.,;:!?') / len(text) if text else 0
        caps_ratio = sum(1 for c in text if c.isupper()) / len(text) if text else 0
        ttr = n_unique / n_words if n_words else 0
        reactions = row.get('ReactionsCount', 0)

        rows.append({
            'Id': row['Id'],
            'avg_word_len': avg_word_len,
            'punct_density': punct_density,
            'caps_ratio': caps_ratio,
            'type_token_ratio': ttr,
            'ReactionsCount': reactions
        })

    return pd.DataFrame(rows)

def cluster_comments(comment_features, k):
    X = comment_features.drop(columns=['Id'])
    X_scaled = StandardScaler().fit_transform(X)
    kmeans = KMeans(n_clusters=k, random_state=42)
    comment_features['cluster'] = kmeans.fit_predict(X_scaled)
    comment_features['style_cluster_name'] = comment_features['cluster'].map(cluster_names)
    return comment_features

# === ESECUZIONE ===

# Carica solo i commenti con stance nota
df = pd.read_csv(input_file)
df = df[df['stance_label'].notna()].copy()

# Estrai le feature stilometriche
comment_features = extract_comment_features(df)

# Esegui il clustering
comment_clusters = cluster_comments(comment_features, n_clusters)

# Associa i cluster al dataframe originale
df = df.merge(comment_clusters[['Id', 'style_cluster_name']], on='Id', how='left')

# Salva il risultato
df.to_csv(output_file, index=False)
print(f"File salvato: {output_file}")

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.cluster import KMeans
from sklearn.preprocessing import StandardScaler

# === PARAMETERS ===
charlie_file = "charliehebdo_classified_fast.csv"
putin_file = "putinmissing_classified_fast.csv"
combined_file = "combined_classified_clustered.csv"
n_clusters = 4

# === CLUSTER NAMES ===
cluster_names = {
    0: "Balanced Commenters",
    1: "High-Frequency Posters",
    2: "Analytical Writers",
    3: "Emphatic Reactors"
}

# === FUNCTIONS ===

def extract_user_features(df):
    df['created_at'] = pd.to_datetime(df['created_at'], errors='coerce')
    user_groups = df.groupby('user_id')
    rows = []

    for user_id, group in user_groups:
        texts = group['text'].dropna().tolist()
        full_text = ' '.join(texts)
        words = full_text.split()
        n_words = len(words)
        n_unique = len(set(words))

        avg_word_len = np.mean([len(w) for w in words]) if words else 0
        punct_density = sum(1 for c in full_text if c in '.,;:!?') / len(full_text) if full_text else 0
        caps_ratio = sum(1 for c in full_text if c.isupper()) / len(full_text) if full_text else 0
        tweet_rate = len(group) / ((group['created_at'].max() - group['created_at'].min()).total_seconds() / 3600 + 1)
        ttr = n_unique / n_words if n_words else 0

        rows.append({
            'user_id': user_id,
            'avg_word_len': avg_word_len,
            'punct_density': punct_density,
            'caps_ratio': caps_ratio,
            'tweet_rate': tweet_rate,
            'type_token_ratio': ttr
        })

    return pd.DataFrame(rows)

def cluster_users(user_features, k):
    X = user_features.drop(columns=['user_id'])
    X_scaled = StandardScaler().fit_transform(X)
    kmeans = KMeans(n_clusters=k, random_state=42)
    user_features['cluster'] = kmeans.fit_predict(X_scaled)
    return user_features

def process_event(file_path, k):
    df = pd.read_csv(file_path, parse_dates=['created_at'])
    df = df[(df['tweet_type'] == 'reaction') & (df['stance_label'].notna())]
    user_features = extract_user_features(df)
    user_clusters = cluster_users(user_features, k)
    user_clusters['cluster_name'] = user_clusters['cluster'].map(cluster_names)
    df = df.merge(user_clusters[['user_id', 'cluster_name']], on='user_id', how='left')
    return df

def calculate_stance_distribution(df, cluster_column):
    stance_counts = df.groupby(cluster_column)['stance_label'].value_counts(normalize=True).unstack().fillna(0)
    stance_counts = stance_counts[["B", "D", "N"]] * 100
    return stance_counts

def plot_cluster_distribution(stance_df, title, ax):
    labels = stance_df.index.tolist()
    x = np.arange(len(labels))
    width = 0.25

    bars_b = ax.bar(x - width, stance_df["B"], width, label="Belief", color="skyblue")
    bars_d = ax.bar(x, stance_df["D"], width, label="Disbelief", color="salmon")
    bars_n = ax.bar(x + width, stance_df["N"], width, label="Neutral", color="lightgray")

    for bars in [bars_b, bars_d, bars_n]:
        for bar in bars:
            height = bar.get_height()
            ax.annotate(f'{height:.1f}%', xy=(bar.get_x() + bar.get_width() / 2, height),
                        xytext=(0, 3), textcoords="offset points", ha='center', va='bottom', fontsize=8)

    ax.set_title(title)
    ax.set_ylabel("Percentage")
    ax.set_xticks(x)
    ax.set_xticklabels(labels, rotation=15)
    ax.legend(title="Stance")

def stance_df_to_latex(df, caption, label):
    df_formatted = df.copy()
    df_formatted = df_formatted.round(1)
    df_formatted.index.name = "Cluster"
    df_formatted.columns = ["Belief (%)", "Disbelief (%)", "Neutral (%)"]

    latex_table = df_formatted.to_latex(
        index=True,
        caption=caption,
        label=label,
        column_format='lccc',
        float_format="%.1f",
        bold_rows=False,
        escape=False
    )
    return latex_table

# === EXECUTION ===

charlie_df = process_event(charlie_file, n_clusters)
charlie_stance = calculate_stance_distribution(charlie_df, cluster_column="cluster_name")

putin_df = process_event(putin_file, n_clusters)
putin_stance = calculate_stance_distribution(putin_df, cluster_column="cluster_name")

combined_df = pd.read_csv(combined_file)
combined_df = combined_df[combined_df["stance_label"].notna()]
combined_stance = calculate_stance_distribution(combined_df, cluster_column="style_cluster_name")

# === PLOT ALL THREE IN A COLUMN ===
fig, axes = plt.subplots(3, 1, figsize=(12, 16))

plot_cluster_distribution(charlie_stance, "Stance per Cluster – Charlie Hebdo", axes[0])
plot_cluster_distribution(putin_stance, "Stance per Cluster – Putin Missing", axes[1])
plot_cluster_distribution(combined_stance, "Stance per Style Cluster – Combined", axes[2])

plt.tight_layout()
plt.show()

# === LATEX TABLES ===

charlie_latex = stance_df_to_latex(
    charlie_stance,
    caption="Percentage distribution of stance types per cluster – Charlie Hebdo",
    label="tab:stance_charlie"
)

putin_latex = stance_df_to_latex(
    putin_stance,
    caption="Percentage distribution of stance types per cluster – Putin Missing",
    label="tab:stance_putin"
)

combined_latex = stance_df_to_latex(
    combined_stance,
    caption="Percentage distribution of stance types per style cluster – Combined Dataset",
    label="tab:stance_combined"
)

# === PRINT TABLES ===
print(charlie_latex)
print("\n" + "="*80 + "\n")
print(putin_latex)
print("\n" + "="*80 + "\n")
print(combined_latex)

import pandas as pd

# === FILES ===
charlie_file = "charliehebdo_classified_fast.csv"
putin_file = "putinmissing_classified_fast.csv"
combined_file = "combined_classified_clustered.csv"

# === CLUSTER NAMES ===
cluster_names = [
    "Balanced Commenters",
    "High-Frequency Posters",
    "Analytical Writers",
    "Emphatic Reactors"
]

# === FUNZIONI ===

def load_and_prepare_event(file_path, user_id_col, text_col, cluster_col=None):
    df = pd.read_csv(file_path)
    df = df[df["stance_label"].notna()]
    if cluster_col is None:
        return df
    else:
        df = df[df[cluster_col].notna()]
        return df[[user_id_col, "stance_label", cluster_col]].copy()

def get_counts(df, cluster_col):
    counts = df.groupby(cluster_col)["stance_label"].value_counts().unstack().fillna(0).astype(int)
    for stance in ["B", "D", "N"]:
        if stance not in counts.columns:
            counts[stance] = 0
    counts = counts[["B", "D", "N"]]
    return counts

def add_missing_clusters(counts, all_clusters):
    for name in all_clusters:
        if name not in counts.index:
            counts.loc[name] = [0, 0, 0]
    return counts.loc[all_clusters]  # Reorder

def build_combined_table(c1, c2, c3):
    combined = pd.concat([
        c1.add_prefix("Charlie "),
        c2.add_prefix("Putin "),
        c3.add_prefix("Combined ")
    ], axis=1)
    combined.index.name = "Cluster"
    return combined

def counts_table_to_latex(df, caption, label):
    df.index.name = "Cluster"
    return df.to_latex(
        index=True,
        caption=caption,
        label=label,
        column_format='l' + 'r' * df.shape[1],
        bold_rows=False
    )

# === PROCESSING ===

# Charlie Hebdo
charlie_df = load_and_prepare_event(charlie_file, "user_id", "text")
charlie_df = charlie_df[(charlie_df["tweet_type"] == "reaction")]
user_cluster = pd.read_csv(charlie_file)[["user_id", "cluster_name"]].dropna().drop_duplicates()
charlie_df = charlie_df.merge(user_cluster, on="user_id", how="left")
charlie_counts = get_counts(charlie_df, "cluster_name")
charlie_counts = add_missing_clusters(charlie_counts, cluster_names)

# Putin Missing
putin_df = load_and_prepare_event(putin_file, "user_id", "text")
putin_df = putin_df[(putin_df["tweet_type"] == "reaction")]
user_cluster = pd.read_csv(putin_file)[["user_id", "cluster_name"]].dropna().drop_duplicates()
putin_df = putin_df.merge(user_cluster, on="user_id", how="left")
putin_counts = get_counts(putin_df, "cluster_name")
putin_counts = add_missing_clusters(putin_counts, cluster_names)

# Combined Dataset
combined_df = load_and_prepare_event(combined_file, "UserId", "Content", cluster_col="style_cluster_name")
combined_counts = get_counts(combined_df, "style_cluster_name")
combined_counts = add_missing_clusters(combined_counts, cluster_names)

# === BUILD FINAL TABLE ===
final_table = build_combined_table(charlie_counts, putin_counts, combined_counts)

# === EXPORT LATEX ===
latex_output = counts_table_to_latex(
    final_table,
    caption="Number of messages per stance type and cluster across three datasets",
    label="tab:stance_counts"
)

# === PRINT RESULT ===
print(latex_output)

import pandas as pd
import numpy as np
from sklearn.cluster import KMeans
from sklearn.preprocessing import StandardScaler

# === PARAMETERS ===
charlie_file = "charliehebdo_classified_fast.csv"
putin_file = "putinmissing_classified_fast.csv"
combined_file = "combined_classified_clustered.csv"
n_clusters = 4

cluster_names = {
    0: "Balanced Commenters",
    1: "High-Frequency Posters",
    2: "Analytical Writers",
    3: "Emphatic Reactors"
}

# === FUNCTIONS ===

def extract_user_features(df):
    df['created_at'] = pd.to_datetime(df['created_at'], errors='coerce')
    user_groups = df.groupby('user_id')
    rows = []

    for user_id, group in user_groups:
        texts = group['text'].dropna().tolist()
        full_text = ' '.join(texts)
        words = full_text.split()
        n_words = len(words)
        n_unique = len(set(words))

        avg_word_len = np.mean([len(w) for w in words]) if words else 0
        punct_density = sum(1 for c in full_text if c in '.,;:!?') / len(full_text) if full_text else 0
        caps_ratio = sum(1 for c in full_text if c.isupper()) / len(full_text) if full_text else 0
        tweet_rate = len(group) / ((group['created_at'].max() - group['created_at'].min()).total_seconds() / 3600 + 1)
        ttr = n_unique / n_words if n_words else 0

        rows.append({
            'user_id': user_id,
            'avg_word_len': avg_word_len,
            'punct_density': punct_density,
            'caps_ratio': caps_ratio,
            'tweet_rate': tweet_rate,
            'type_token_ratio': ttr
        })

    return pd.DataFrame(rows)

def cluster_users(user_features, k):
    X = user_features.drop(columns=['user_id'])
    X_scaled = StandardScaler().fit_transform(X)
    kmeans = KMeans(n_clusters=k, random_state=42)
    user_features['cluster'] = kmeans.fit_predict(X_scaled)
    user_features['cluster_name'] = user_features['cluster'].map(cluster_names)
    return user_features

def get_stance_counts(df, cluster_col):
    counts = df.groupby(cluster_col)['stance_label'].value_counts().unstack().fillna(0).astype(int)
    for col in ["B", "D", "N"]:
        if col not in counts.columns:
            counts[col] = 0
    return counts[["B", "D", "N"]]

def ensure_all_clusters(counts, names):
    for name in names:
        if name not in counts.index:
            counts.loc[name] = [0, 0, 0]
    return counts.loc[names]

# === CHARLIE ===
charlie_raw = pd.read_csv(charlie_file)
charlie_raw = charlie_raw[(charlie_raw['tweet_type'] == 'reaction') & (charlie_raw['stance_label'].notna())]
charlie_features = extract_user_features(charlie_raw)
charlie_clusters = cluster_users(charlie_features, n_clusters)
charlie_merged = charlie_raw.merge(charlie_clusters[['user_id', 'cluster_name']], on='user_id', how='left')
charlie_counts = get_stance_counts(charlie_merged, 'cluster_name')
charlie_counts = ensure_all_clusters(charlie_counts, cluster_names.values())

# === PUTIN ===
putin_raw = pd.read_csv(putin_file)
putin_raw = putin_raw[(putin_raw['tweet_type'] == 'reaction') & (putin_raw['stance_label'].notna())]
putin_features = extract_user_features(putin_raw)
putin_clusters = cluster_users(putin_features, n_clusters)
putin_merged = putin_raw.merge(putin_clusters[['user_id', 'cluster_name']], on='user_id', how='left')
putin_counts = get_stance_counts(putin_merged, 'cluster_name')
putin_counts = ensure_all_clusters(putin_counts, cluster_names.values())

# === COMBINED ===
combined_raw = pd.read_csv(combined_file)
combined_df = combined_raw[combined_raw['stance_label'].notna()]
combined_counts = get_stance_counts(combined_df, 'style_cluster_name')
combined_counts = ensure_all_clusters(combined_counts, cluster_names.values())

# === CONCATENATE TABLE ===
final_table = pd.concat([
    charlie_counts.add_prefix("Charlie "),
    putin_counts.add_prefix("Putin "),
    combined_counts.add_prefix("Combined ")
], axis=1)
final_table.index.name = "Cluster"

# === EXPORT TO LATEX ===
latex = final_table.to_latex(
    index=True,
    caption="Number of messages per stance type and cluster across three datasets",
    label="tab:stance_counts",
    column_format="lrrrrrrr"
)

# === PRINT RESULT ===
print(latex)

import pandas as pd

# === INPUT: valori DeepFake (commenti) per cluster ===
data = {
    "Cluster": ["Balanced Commenters", "High-Frequency Posters", "Analytical Writers", "Emphatic Reactors"],
    "B_i": [16, 0, 51, 240],   # Believers
    "U_i": [17, 0, 60, 156],   # Unbelievers
    "Nn_i": [64, 19, 111, 480] # Neutrals
}

df = pd.DataFrame(data)

# === CALCOLI ===
df["N_i"] = df["B_i"] + df["U_i"] + df["Nn_i"]  # total users
df["Pi"] = df["B_i"] / df["N_i"]                # penetration rate
df["Si"] = df["Nn_i"] / df["N_i"]               # susceptible rate
df["Ui_ratio"] = df["U_i"] / df["N_i"]          # resistance ratio

# Parametri
rho_i = 1.0   # social amplification factor
eta = 1.0     # influence of unbelievers

# Calcolo rischio
df["R_i"] = df["Pi"] * df["Si"] * rho_i * (1 - eta * df["Ui_ratio"])

# Output finale
print(df[["Cluster", "N_i", "Pi", "Si", "Ui_ratio", "R_i"]].to_string(index=False))

import pandas as pd

# === INPUT: dati per ciascun caso studio ===
data = {
    "Cluster": ["Balanced Commenters", "High-Frequency Posters", "Analytical Writers", "Emphatic Reactors"],
    "Charlie_B": [255, 123, 82, 9],
    "Charlie_D": [2171, 1145, 374, 59],
    "Charlie_N": [1317, 759, 535, 58],
    "Putin_B": [1, 14, 5, 4],
    "Putin_D": [7, 83, 28, 8],
    "Putin_N": [23, 84, 52, 52],
    "DeepFake_B": [16, 0, 51, 240],
    "DeepFake_D": [17, 0, 60, 156],
    "DeepFake_N": [64, 19, 111, 480],
}

df = pd.DataFrame(data)

# === PARAMETRI ===
rho = 1.0  # amplification factor
eta = 1.0  # resistance effect

# === FUNZIONE DI CALCOLO RISCHIO ===
def compute_risk(B, D, N):
    N_total = B + D + N
    if N_total == 0:
        return 0.0
    Pi = B / N_total
    Si = N / N_total
    Ui = D / N_total
    Ri = Pi * Si * rho * (1 - eta * Ui)
    return round(Ri, 5)

# === CALCOLO PER OGNI CASO STUDIO ===
for case in ["Charlie", "Putin", "DeepFake"]:
    df[f"{case}_R"] = df.apply(
        lambda row: compute_risk(row[f"{case}_B"], row[f"{case}_D"], row[f"{case}_N"]), axis=1
    )

# === OUTPUT FINALE ===
output_cols = ["Cluster", "Charlie_R", "Putin_R", "DeepFake_R"]
df_result = df[output_cols]
print(df_result.to_string(index=False))